### ISSUE TITLE
filter shown variants and indels >x%

### ISSUE THREAD

**Issue by nbx0** [nbx0/IRMA-SPY#43]

**Comment by kristinelacek** [comment]
this can be set in the irma config itself

**Comment by nbx0** [comment]
true, I was thinking to leave the whole data there (and deliver it in the excel DL), but just have the dash-dataframe start the view auto filtered. It think that is what I did on minor vars...

**Comment by nbx0** [comment]
but yeah, I agree that we should config IRMA to ignore stuff below x%... Probably 5% for ONT...

**Comment by kristinelacek** [comment]
https://github.com/CDCgov/spyne/commit/fb63b669f0d34cd3b24802133a3e690f63cfea52
